feature/message_history
ostis-apps/nika pull request #249
Opened 2023-06-28 14:01 UTC by PetrochukKsenija

2023-07-13 10:02 UTC, MksmOrlov requested changes

2023-07-13 10:02 UTC, MksmOrlov commented on problem-solver/cxx/dialogControlModule/agent/MessageHistoryGenerationAgent.hpp
> +  bool checkActionClass(const ScAddr & actionNode);
According to the codestyle
```suggestion
  bool checkActionClass(ScAddr const & actionNode);
```

2023-07-13 10:02 UTC, MksmOrlov commented on problem-solver/cxx/dialogControlModule/generator/MessageHistoryGenerator.cpp
> +  //   SC_THROW_EXCEPTION(ExceptionItemNotFound, "Can't add message to dialog. Author addr is not valid");
remove commented code

2023-07-13 10:02 UTC, MksmOrlov commented on problem-solver/cxx/dialogControlModule/keynodes/MessageKeynodes.hpp
> +
remove this space

2023-07-13 10:02 UTC, MksmOrlov commented on kb/section_subject_domain_of_dialogues/section_subject_domain_of_dialog_control/examples/message_processing_program.scs
You may not change scs program. It is already removed on develop. You can rebase on develop to get actual state

2023-07-18 18:42 UTC, MksmOrlov requested changes
1. Fix old unresolved comments
2. Fix new comments
3. Rebase on develop

2023-07-18 18:42 UTC, MksmOrlov commented on docs/agents/messageHistoryGenerationAgent.md
rename file

2023-07-18 18:42 UTC, MksmOrlov commented on docs/index.md
> +    * [Message history generation agent](agents/messageHistoryGenerationAgent.md)
And rename page

2023-07-18 18:42 UTC, MksmOrlov commented on problem-solver/cxx/dialogControlModule/agent/MessageHistoryGenerationAgent.cpp
> +SC_AGENT_IMPLEMENTATION(MessageHistoryGenerationAgent)
Rename the agent and the file according to the action class

2023-07-18 18:42 UTC, MksmOrlov commented on problem-solver/cxx/dialogControlModule/agent/MessageHistoryGenerationAgent.cpp
> +  generator.addMessageToDialog(dialogAddr, message);
Make try catch. You throw exception in the generator method

2023-07-18 20:50 UTC, PetrochukKsenija commented on problem-solver/cxx/dialogControlModule/CMakeLists.txt
> +
i had removed this lines

2023-07-25 11:33 UTC, MksmOrlov requested changes

2023-07-26 09:22 UTC, MksmOrlov requested changes

2023-07-26 09:22 UTC, MksmOrlov commented on kb/section_subject_domain_of_dialogues/section_subject_domain_of_dialog_control/examples/message_processing_program.gwf
After action_find_word_in_set_by_first_letter must be **nrel_goto**, not **nrel_then**. The system doesn't answer. The same as in develop
![image](https://github.com/ostis-apps/nika/assets/36566977/1864fd57-1263-4c13-9227-84c5dd3c068f)

2023-07-26 09:22 UTC, MksmOrlov commented on kb/test_dialog.scs
> +    [тестовый дилог]
```suggestion
    [тестовый диалог]
```

2023-07-26 10:20 UTC, MksmOrlov requested changes

2023-07-26 10:20 UTC, MksmOrlov commented on problem-solver/cxx/messageReplyModule/generator/MessageHistoryGenerator.cpp
>        ScType::EdgeAccessConstPosPerm,
```suggestion
      ScType::EdgeAccessConstPosTemp,
```
Check all arcs to be temporal
![image](https://github.com/ostis-apps/nika/assets/36566977/45908292-0d68-48ae-9165-91a9ff0642ec)

2023-07-26 10:23 UTC, MksmOrlov commented on problem-solver/cxx/messageReplyModule/generator/MessageHistoryGenerator.cpp
>        ScType::EdgeAccessConstPosPerm,
Remove duplicated generator in message reply module

2023-07-28 17:51 UTC, MksmOrlov requested changes

2023-07-28 17:51 UTC, MksmOrlov commented on problem-solver/cxx/messageReplyModule/test/agent/GenerateReplyMessageAgent.hpp
What happened to this file? ^)

2023-07-28 17:51 UTC, MksmOrlov commented on docs/agents/images/addMessageToTheDialogAgentOutputDialog.png
I can't find constructions like at the image (nrel_dialogue_history, participants, nika).
![image](https://github.com/ostis-apps/nika/assets/36566977/2fe989c1-0c48-4d89-8b74-0b6d6b170e5e)
1. Create constructions like at the image. See `interface/src/api/sc/agents/resolveUserAgent.ts`, replace `rrel_dialog_participants` with `nrel_dialog_participants`
2. Rename `nrel_dialog_history` in the image to the `nrel_dialogue_history`

2023-08-30 11:53 UTC, MksmOrlov requested changes
- Formalize nrel_dialogue_history
- Rebase on develop and add russian documentation

2023-08-31 08:09 UTC, MksmOrlov requested changes

2023-08-31 08:09 UTC, MksmOrlov commented on kb/extra/nrel_dialogue_history.scs
> +	[Dialogue history*] (* <- lang_en;; *);;
endline

2023-08-31 08:09 UTC, MksmOrlov commented on docs/agents/addMessageToTheDialogAgent.ru.md
> +Данный агент добавляет сообщение в диалога.
в диалог

2023-08-31 08:09 UTC, MksmOrlov commented on docs/agents/addMessageToTheDialogAgent.ru.md
> +* Если история диалогов пуста, то к первому добавленному сообщению будет добавлено отношение `rrel_1`. Последнее сообщение всегда имеет отношение `rel_last`. Между сообщениями существует отношение `n
Если история диалог**а**

2023-08-31 08:09 UTC, MksmOrlov commented on docs/agents/addMessageToTheDialogAgent.ru.md
> +Пример структуры ввода для добавления пользовательского сообщения в диалог:
Пример входной структуры. Для добавления сообщения пользователя

2023-08-31 08:09 UTC, MksmOrlov commented on docs/agents/addMessageToTheDialogAgent.ru.md
> +Пример структуры ввода для добавления сообщения системы в диалог:
Пример входной структуры

2023-08-31 08:09 UTC, MksmOrlov commented on docs/agents/addMessageToTheDialogAgent.ru.md
> +Пример полученной структуры:
Пример выходной структуры

2023-08-31 11:24 UTC, merged