docs: add russian language
ostis-apps/nika pull request #262
Opened 2023-07-28 10:42 UTC by MakarenkoAI

2023-07-28 17:40 UTC, MksmOrlov requested changes

2023-07-29 08:30 UTC, MakarenkoAI commented on docs/build/linux-build.ru.md
> +  - У Вас может появиться ошибка при запуске следующего скрипта:
я не сохранила ошибку, которая тогда была, поэтому и не написала, какая именно

2023-07-29 20:20 UTC, MksmOrlov requested changes
And check unresolved

2023-07-29 20:20 UTC, MksmOrlov commented on docs/agents/standardMessageReplyAgent.ru.md
> +Собирает логические правила и целевой шаблон, затем пересылает информацию Direct Inference Agent (агенту из подсистемы scl-machine) для дальнейшей обработки. Вы можете узнать больше про Direct Infere
```suggestion
Собирает логические правила и целевой шаблон, затем пересылает информацию DirectInferenceAgent (агенту из подсистемы scl-machine) для дальнейшей обработки. Вы можете узнать больше про DirectInferenceAgent в документации [scl-machine](../subsystems/scl-machine.md). Затем он вызывает PhraseGenerationAgent, чтобы создать sc-ссылку с текстом ответного сообщения.
```

2023-07-29 20:20 UTC, MksmOrlov commented on docs/changelog.ru.md
> +- Предметная область для интеллектуальных систем обучения
```suggestion
- Предметная область интеллектуальных обучающих систем
```

2023-07-29 20:20 UTC, MksmOrlov commented on docs/changelog.ru.md
> +- Предметная область для для сообщений
```suggestion
- Предметная область диалогов
- Предметная область сообщений
```

2023-07-29 20:20 UTC, MksmOrlov commented on docs/thirdparty.ru.md
> +Проект создан на основе [ostis-example-app](http://ostis-ai.github.io/sc-machine/) и использует технологию OSTIS.
```suggestion
Проект создан на основе [ostis-example-app](http://ostis-ai.github.io/sc-machine/) и использует Технологию OSTIS.
```

2023-07-30 15:23 UTC, MksmOrlov requested changes

2023-07-30 15:23 UTC, MksmOrlov commented on docs/dev/codestyle.ru.md
> +
Add also information about formatting script:

_Чтобы отформатировать все C/C++ файлы проекта автоматически, используйте скрипт `./scripts/clang/format_code.sh`_

2023-07-30 15:23 UTC, MksmOrlov commented on docs/dev/codestyle.ru.md
> +- Используйте порядок справа налево для переменных/параметров: `Src Addr const & addr` (ссылка на константу `SrcAddr`).
```suggestion
- Используйте порядок справа налево для переменных/параметров: `ScAddr const & addr` (ссылка на константу `ScAddr`).
```

2023-07-31 06:35 UTC, MksmOrlov approved these changes

2023-07-31 16:10 UTC, MikhailSadovsky requested changes

2023-07-31 16:10 UTC, MikhailSadovsky commented on docs/agents/changeInterfaceColorAgent.ru.md
> +Чтобы протестировать, Вы можете использовать следующие сообщения: `Измени цвет хедера на #001122`, `Поменяй цвет компонента футер на #CC1122` или `Измени цвет компонента основная часть на #00AAFF`.
I suggest to move this up even before action class for user to see how to test it

2023-07-31 16:10 UTC, MikhailSadovsky commented on docs/agents/findWordInSetByFirstLetter.ru.md
> +Чтобы протестировать, Вы можете использовать следующее сообщение: `Что в примере начинается на букву А?` или использовать другую букву.
Suggest to move it up as previous

2023-07-31 16:10 UTC, MikhailSadovsky commented on docs/build/docker-build.ru.md
> +Если Вы не хотите пересобирать БЗ при повторном запуске, то закомментируйте переменную окружения `REBUILD_KB` в `docker-compose.yml`.
Suggest to add troubleshooting notes from README
![image](https://github.com/ostis-apps/nika/assets/8840551/81d81a07-b2a9-491a-bccf-ab1890c56222)

2023-08-01 14:36 UTC, MikhailSadovsky approved these changes

2023-08-02 10:13 UTC, merged