feature(kb): what nika can
ostis-apps/nika pull request #263
Opened 2023-08-03 08:49 UTC by MakarenkoAI

2023-08-03 09:46 UTC, MksmOrlov requested changes
Update changelog, update documentation

2023-08-03 09:46 UTC, MksmOrlov commented on kb/section_subject_domain_of_intelligent_study_systems/relations/nrel_skill.scs
> +    (* <- lang_ru;; *);;
Add Enlish main idtf

2023-08-03 09:46 UTC, MksmOrlov commented on kb/section_subject_domain_of_dialogues/section_subject_domain_of_dialog_control/section_subject_domain_of_dialogue_control_using_template_responses/logic_rules/lr_alternative_classification/lr_message_about_skills.gwf
align constructions please

2023-08-03 09:46 UTC, MksmOrlov commented on kb/section_subject_domain_of_dialogues/section_subject_domain_of_dialog_control/section_subject_domain_of_dialogue_control_using_template_responses/logic_rules/lr_message_about_skills/lr_message_about_skills.gwf
align constructions please

2023-08-03 09:46 UTC, MksmOrlov commented on kb/section_subject_domain_of_messages/subject_domain_of_phrases/examples/concept_phrase_about_skills/concept_phrase_about_skills.gwf
align constructions please

2023-08-03 09:46 UTC, MksmOrlov commented on kb/section_subject_domain_of_intelligent_study_systems/concepts/instances/nika_docs/nika.scs
> +    и "Какой срок сдачи первой лабы?";
Remove 'Какой срок сдачи первой лабы?', it is broken)

2023-08-03 09:46 UTC, MksmOrlov commented on kb/section_subject_domain_of_intelligent_study_systems/concepts/instances/nika_docs/nika.scs
> +    изменять цвет компонентов интерфейса: "Измени цвет футера на #00bfff",
Write what components we can change: main part, footer and header

2023-08-03 09:46 UTC, MksmOrlov commented on kb/section_subject_domain_of_intelligent_study_systems/concepts/instances/nika_docs/nika.scs
> +    отвечать на вопросы про условия и сроки лабораторных работ: "Что нужно делать в первой лабе?"
Remove "Что нужно делать в первой лабе?", it is broken. Add it later, when fixed

2023-08-03 19:12 UTC, MksmOrlov requested changes

2023-08-03 19:12 UTC, MksmOrlov commented on docs/changelog.md
> +- Common rule to answer "Что умеет Ника?"
It is not common. Just "Answer "Что умеет Ника?""

2023-08-03 19:12 UTC, MksmOrlov commented on kb/section_subject_domain_of_intelligent_study_systems/concepts/instances/nika_docs/nika.scs
> +    а также я могу научиться отвечать на любые новые вопросы.]
Nika or I?
![image](https://github.com/ostis-apps/nika/assets/36566977/b2763206-8457-407a-b6c4-458af02d6104)

2023-08-04 08:07 UTC, MksmOrlov approved these changes

2023-08-04 13:54 UTC, MikhailSadovsky approved these changes

2023-08-04 13:57 UTC, merged