[agents] Update agents api
ostis-apps/nika pull request #346
Opened 2024-09-20 09:00 UTC by MakarenkoAI

2024-10-04 11:00 UTC, kilativ-dotcom requested changes
nothing happens in chat
![image](https://github.com/user-attachments/assets/c1d1802c-fe26-4f7f-bf10-58712ab86c40)

2024-10-06 14:28 UTC, MikhailSadovsky commented on repo/strings1.scdb
Is this really should be committed?

2024-10-06 14:28 UTC, MikhailSadovsky commented on scripts/run_sc_machine.sh
Should run_sc_server script be removed?

2024-10-06 14:32 UTC, ProtasSemyon commented on scripts/run_sc_machine.sh
No, run_py_tests.sh won't work without it.

2024-10-06 14:35 UTC, ProtasSemyon commented on repo/strings1.scdb
fixed

2024-10-06 14:41 UTC, MikhailSadovsky approved these changes

2024-10-07 07:45 UTC, kilativ-dotcom approved these changes
it works, but some logs are missing entity names

2024-10-07 07:45 UTC, kilativ-dotcom commented on problem-solver/cxx/dialogControlModule/agent/PhraseGenerationAgent.cpp
> +  ScAddr const phraseStruct = m_context.GenerateNode(ScType::NodeStruct);
it is still without specified constancy

2024-10-07 07:45 UTC, kilativ-dotcom commented on problem-solver/cxx/dialogControlModule/searcher/MessageSearcher.cpp
> +    SC_LOG_DEBUG("The first message node found");
log without name

2024-10-12 11:13 UTC, ProtasSemyon commented on problem-solver/cxx/commonModule/handler/NumberHandler.cpp
> +  SC_LOG_DEBUG("NumberHandler: Found " << std::to_string(candidateList.size()) << " sc-link with content " << numberAsString);
Implement the getClassNameForLog() method and use it instead of repeating the class name everywhere. Fix it in all locations

2024-10-31 08:08 UTC, merged